package Topics.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class DurationTopic_Constraints extends BaseConstraintsDescriptor {
  public DurationTopic_Constraints() {
    super(CONCEPTS.DurationTopic$rK);
  }

  public static class Duration_Property extends BasePropertyConstraintsDescriptor {
    public Duration_Property(ConstraintsDescriptor container) {
      super(PROPS.duration$15Q0, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:b6d5f271-9f84-48cb-9e62-6e0ba8a92283(Topics.constraints)", "1647811562846779143"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      if (propertyValue > 0 && propertyValue < 61) {
        return true;
      }
      return false;
    }
  }
  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(PROPS.duration$15Q0, new Duration_Property(this));
    return properties;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept DurationTopic$rK = MetaAdapterFactory.getConcept(0xda1db77ac2614742L, 0xa032c8bcb93769c9L, 0x2e23a5d8c824c93bL, "Topics.structure.DurationTopic");
  }

  private static final class PROPS {
    /*package*/ static final SProperty duration$15Q0 = MetaAdapterFactory.getProperty(0xda1db77ac2614742L, 0xa032c8bcb93769c9L, 0x2e23a5d8c824c93bL, 0x2e23a5d8c824cf3eL, "duration");
  }
}
