package Topics.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Conference_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new DurationTopic_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new LightningTopic_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xda1db77ac2614742L, 0xa032c8bcb93769c9L, 0x2e23a5d8c824d96eL), MetaIdFactory.conceptId(0xda1db77ac2614742L, 0xa032c8bcb93769c9L, 0x2e23a5d8c824c93bL), MetaIdFactory.conceptId(0xda1db77ac2614742L, 0xa032c8bcb93769c9L, 0x2e23a5d8c824d14aL)).seal();
}
